# implicitly
function_parameter_count: 8
cyclomatic_complexity: 15
file_length: 600
function_body_length: 60
type_body_length: 400
large_tuple: 4


disabled_rules: # rule identifiers to exclude from running
- trailing_whitespace
- line_length
#- empty_enum_arguments
#- fallthrough
- syntactic_sugar
excluded: # paths to ignore during linting. Takes precedence over `included`.
- Pods


